name: fiches
version: '1.0.1'
services:
  mongodb:
    container_name: fiches_mongodb
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGODB_DATABASE=fiches
    ports:
      - 27017:27017
    volumes:
      - type: bind
        source: fiches_data
        target: /data/db

  backend:
    container_name: fiches_backend
    image: back-end
    build:
      context: back-end

    ports:
      - 3030:3030

    environment:
      - MONGODB_URI=mongodb://user:pass@mongodb:27017/
      - DB_NAME=fiches
      - URL=localhost:3030
    depends_on:
      - mongodb

  front-end:
    container_name: fiches_frontend
    image: front-end
    build:
      context: front-end

    environment:
      - PUBLIC_BACKEND=http://backend:3030/api
    ports:
      - 5173:5173
      - 8081:5173
    depends_on:
      - backend
